version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:14.17.0
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Start application
          command: npm start
          background: true

workflows:
  version: 2
  build:
    jobs:
      - build
