version: 2.1

orbs:
  node: .circleci/node@4.7.0

jobs:
  build:
    docker:
      - image: cimg/node:14.17.0
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  build:
    jobs:
      - build
