version: 2.1

jobs:
  build-and-run:
    docker:
      - image: docker:19.03.12
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - run:
          name: Build Docker Image
          command: |
            docker build -t node-app .
      - run:
          name: Run Docker Container
          command: |
            docker run -d -p 8080:8080 node-app

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-run
